package com.example.yanivbot.Models;

public enum ConversationState {
    START,
    AWAITING_TAXI_CONFIRMATION,
    TAXI_SERVICE,
    TAXI_PICKUP,
    TAXI_DESTINATION,
    CONFIRMATION,
    
    GROUP_MESSAGE,
    
    BUSINESS_MENU,
    DELIVERY_CUSTOMER_PHONE,
    DELIVERY_ADDRESS,
    DELIVERY_READY_TIME,
    DELIVERY_PRICE,
    DELIVERY_NOTES,
}
