

#spring.config.import=optional:classpath:application-local.properties
#spring.application.name=Yanivbot


#railway timing issues solution:
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.datasource.url=jdbc:mysql://localhost:3306/yaniv_bot?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

admin.phones=${ADMIN_PHONES}

bot.active=true

# Order Dispatch Configuration
# Distance radius in kilometers for sending orders to nearby drivers
dispatch.radius.km=15.0

delivery.dispatch.before.minutes=${DELIVERY_DISPATCH_BEFORE_MINUTES:5}

whatsapp.provider=meta
whatsapp.verify-token=${WHATSAPP_VERIFY_TOKEN}
whatsapp.access-token=${WHATSAPP_ACCESS_TOKEN}
whatsapp.phone-number-id=${WHATSAPP_PHONE_NUMBER_ID}
whatsapp.api-version=v23.0
whatsapp.webhook-verify-token=${WHATSAPP_WEBHOOK_VERIFY_TOKEN}


google.maps.api-key=${GOOGLE_MAPS_API_KEY}

google.sheets.id=${GOOGLE_SHEETS_ID}
google.sheets.credentials-path=/app/src/main/resources/credentials.json
#google.sheets.credentials-content=${GOOGLE_SHEETS_CREDENTIALS_CONTENT}
google.sheets.credentials-content-base64=${GOOGLE_SHEETS_CREDENTIALS_CONTENT_BASE64}